modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/fpbrault/bluemap3d-patches/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${description}'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="bluemap"
type="required"
versionRange="${bluemap_version_range}"
ordering="AFTER"
side="SERVER"

[[dependencies.${mod_id}]]
modId="bluemap3d"
type="required"
versionRange="[${version},)"
ordering="AFTER"
side="SERVER"
