package dev.duzo.bluemap3d.bake;

import net.minecraft.core.Direction;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.Property;
import net.minecraft.world.phys.Vec3;

import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Dedicated-server reconstruction for Create: Bits 'n' Bobs / Strut Your Stuff girder struts.
 *
 * <p>The endpoint attachment is a normal JSON model. The span is generated by Strut Your Stuff's
 * block-entity renderer from the Connections list. We keep the endpoint model untouched and reuse
 * Bits and Bobs' real girder/cable segment model for the dynamic span rather than drawing a generic prism.
 */
public final class BitsNBobsStrutSource implements BlockModelSource {
    private static final Logger LOGGER = LoggerFactory.getLogger("BlueMap3D/BitsNBobsStrut");
    private static final Set<String> TRACED = ConcurrentHashMap.newKeySet();
    private static final double SURFACE_OFFSET = 6.0 / 16.0;
    private static final String SAFE_GIRDER = "bluemap3d:bits_n_bobs_girder_safe";
    private static final String SAFE_WEATHERED = "bluemap3d:bits_n_bobs_weathered_girder_safe";
    private static final String SAFE_CABLE = "bluemap3d:bits_n_bobs_cable_safe";

    private final ResourcePackSource models;

    public BitsNBobsStrutSource(ResourcePackSource models) {
        this.models = models;
    }

    @Override
    public List<ModelQuad> quadsFor(BlockState state) {
        return List.of();
    }

    @Override
    public List<ModelQuad> quadsFor(BlockState state, CompoundTag metadata) {
        String id = BuiltInRegistries.BLOCK.getKey(state.getBlock()).toString();
        String segmentModel = switch (id) {
            case "bits_n_bobs:girder_strut" -> "bits_n_bobs:block/girder_strut/girder";
            case "bits_n_bobs:weathered_girder_strut" -> "bits_n_bobs:block/girder_strut/weathered_girder";
            case "bits_n_bobs:cable_girder_strut" -> "bits_n_bobs:block/girder_strut/cable";
            default -> null;
        };
        if (segmentModel == null) return List.of();
        String safeTexture = safeTextureKey(id);

        List<ModelQuad> out = new ArrayList<>();

        // Do not pass the mod-resolved texture ids through directly. Some BlueMap asset
        // configurations can resolve the model JSON while returning Minecraft's
        // magenta/black missing sprite for one or more referenced PNGs. Route every strut
        // face through a controlled sentinel instead.
        for (ModelQuad quad : models.quadsFor(state)) {
            out.add(withTexture(quad, safeTexture));
        }

        if (metadata == null || !metadata.contains("Connections", Tag.TAG_LIST)) {
            return out.isEmpty() ? List.of() : List.copyOf(out);
        }

        List<ModelQuad> rawSegment = models.quadsForModel(ResourceLocation.parse(segmentModel), Map.of());
        List<ModelQuad> segment = new ArrayList<>(rawSegment.size());
        for (ModelQuad quad : rawSegment) {
            segment.add(withTexture(quad, safeTexture));
        }
        if (segment.isEmpty()) {
            return out.isEmpty() ? List.of() : List.copyOf(out);
        }

        Direction facing = Direction.byName(stringProperty(state, "facing"));
        if (facing == null) facing = Direction.UP;

        Vec3 start = Vec3.atCenterOf(net.minecraft.core.BlockPos.ZERO)
                .relative(facing, -SURFACE_OFFSET);

        ListTag connections = metadata.getList("Connections", Tag.TAG_COMPOUND);
        if (TRACED.add(id)) {
            LOGGER.debug("V21 strut={} metadata=present connections={} endpointQuads={} segmentQuads={} textureKey={}",
                    id, connections.size(), out.size(), segment.size(), safeTexture);
        }
        for (Tag entry : connections) {
            if (!(entry instanceof CompoundTag connection)) continue;

            int dx = connection.getInt("X");
            int dy = connection.getInt("Y");
            int dz = connection.getInt("Z");
            if (dx == 0 && dy == 0 && dz == 0) continue;

            Direction peerFacing = connection.contains("Facing", Tag.TAG_INT)
                    ? Direction.from3DDataValue(connection.getInt("Facing"))
                    : facing.getOpposite();

            Vec3 end = new Vec3(dx + 0.5, dy + 0.5, dz + 0.5)
                    .relative(peerFacing, -SURFACE_OFFSET);

            // Strut Your Stuff renders each endpoint's half of the connection. Doing the same
            // keeps the scene stable when only one endpoint is present in a captured volume.
            Vec3 midpoint = start.add(end).scale(0.5);
            appendSegment(out, segment, start, midpoint, facing);
        }

        return out.isEmpty() ? List.of() : List.copyOf(out);
    }

    @Override
    public BufferedImage texture(String texture) {
        if (SAFE_GIRDER.equals(texture)) {
            return firstUsable(
                    "create:block/girder",
                    "bits_n_bobs:block/girder_attachment",
                    "create:block/industrial_iron_block");
        }
        if (SAFE_WEATHERED.equals(texture)) {
            return firstUsable(
                    "bits_n_bobs:block/weathered_girder",
                    "bits_n_bobs:block/weathered_girder_attachment",
                    "bits_n_bobs:block/weathered_industrial_iron_block",
                    "create:block/industrial_iron_block");
        }
        if (SAFE_CABLE.equals(texture)) {
            return firstUsable(
                    "bits_n_bobs:block/cable",
                    "create:block/industrial_iron_block");
        }
        BufferedImage image = models.texture(texture);
        return isUsableTexture(image) ? image : generatedIron();
    }

    private BufferedImage firstUsable(String... candidates) {
        for (String candidate : candidates) {
            BufferedImage image = models.texture(candidate);
            if (isUsableTexture(image)) return image;
        }
        return generatedIron();
    }

    private static boolean isUsableTexture(BufferedImage image) {
        if (image == null || image.getWidth() <= 0 || image.getHeight() <= 0) return false;

        // Detect Minecraft-style magenta/black missing-texture sprites. This intentionally
        // runs only inside the B&B strut source, where a magenta/black texture is never a
        // legitimate material.
        int samples = 0;
        int magenta = 0;
        int dark = 0;
        int stepX = Math.max(1, image.getWidth() / 16);
        int stepY = Math.max(1, image.getHeight() / 16);
        for (int y = 0; y < image.getHeight(); y += stepY) {
            for (int x = 0; x < image.getWidth(); x += stepX) {
                int rgb = image.getRGB(x, y);
                int r = (rgb >>> 16) & 0xFF;
                int g = (rgb >>> 8) & 0xFF;
                int b = rgb & 0xFF;
                samples++;
                if (r > 150 && b > 120 && g < 100) magenta++;
                if (r < 55 && g < 55 && b < 55) dark++;
            }
        }
        return !(samples > 0 && magenta * 5 > samples && dark * 5 > samples);
    }

    private static BufferedImage generatedIron() {
        BufferedImage image = new BufferedImage(16, 16, BufferedImage.TYPE_INT_ARGB);
        for (int y = 0; y < 16; y++) {
            for (int x = 0; x < 16; x++) {
                int base = ((x / 4 + y / 4) & 1) == 0 ? 0xFF5F6568 : 0xFF4E5457;
                if (x == 0 || y == 0 || x == 15 || y == 15) base = 0xFF34393B;
                image.setRGB(x, y, base);
            }
        }
        return image;
    }

    private static String safeTextureKey(String id) {
        return switch (id) {
            case "bits_n_bobs:weathered_girder_strut" -> SAFE_WEATHERED;
            case "bits_n_bobs:cable_girder_strut" -> SAFE_CABLE;
            default -> SAFE_GIRDER;
        };
    }

    private static ModelQuad withTexture(ModelQuad quad, String texture) {
        return new ModelQuad(
                quad.cullFace(),
                quad.shadeFace(),
                quad.positions().clone(),
                quad.uvs().clone(),
                texture,
                quad.tint());
    }

    @Override
    public boolean occludes(BlockState state) {
        return false;
    }

    private static void appendSegment(
            List<ModelQuad> out,
            List<ModelQuad> segment,
            Vec3 startBlocks,
            Vec3 endBlocks,
            Direction attachmentFacing) {
        Vec3 span = endBlocks.subtract(startBlocks);
        double length = span.length();
        if (length < 1.0e-4) return;

        Vec3 forward = span.scale(1.0 / length);

        // Use the attachment normal to choose roll whenever possible. This matches the way
        // the client renderer anchors the girder to the endpoint better than a global-up basis.
        Vec3 attachmentNormal = Vec3.atLowerCornerOf(attachmentFacing.getNormal());
        Vec3 up = attachmentNormal.subtract(forward.scale(attachmentNormal.dot(forward)));
        if (up.lengthSqr() < 1.0e-6) {
            Vec3 fallback = Math.abs(forward.y) < 0.95 ? new Vec3(0, 1, 0) : new Vec3(1, 0, 0);
            up = fallback.subtract(forward.scale(fallback.dot(forward)));
        }
        up = up.normalize();
        Vec3 right = up.cross(forward).normalize();

        for (ModelQuad quad : segment) {
            float[] src = quad.positions();
            float[] dst = new float[src.length];
            for (int i = 0; i < 4; i++) {
                double sx = (src[i * 3] - 8.0) / 16.0;
                double sy = (src[i * 3 + 1] - 8.0) / 16.0;
                double sz = src[i * 3 + 2] / 16.0;
                Vec3 p = startBlocks
                        .add(right.scale(sx))
                        .add(up.scale(sy))
                        .add(forward.scale(sz * length))
                        .scale(16.0);
                dst[i * 3] = (float) p.x;
                dst[i * 3 + 1] = (float) p.y;
                dst[i * 3 + 2] = (float) p.z;
            }
            out.add(new ModelQuad(
                    null,
                    null,
                    dst,
                    quad.uvs().clone(),
                    quad.texture(),
                    quad.tint()));
        }
    }

    private static String stringProperty(BlockState state, String name) {
        for (Property<?> property : state.getProperties()) {
            if (property.getName().equals(name)) return valueName(state, property);
        }
        return "";
    }

    private static <T extends Comparable<T>> String valueName(BlockState state, Property<T> property) {
        return property.getName(state.getValue(property));
    }
}